# Generated by Django 3.1.2 on 2024-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
